spring.application.name=ms-ne-gestionpersonas

spring.r2dbc.url=r2dbc:mssql://valdezv231.database.windows.net:1433/free-sql-db-1180422?encrypt=true&trustServerCertificate=false&hostNameInCertificate=*.database.windows.net
spring.r2dbc.username=valdezv231
spring.r2dbc.password=72757455aS*

logging.level.org.springframework.data.r2dbc=DEBUG